name: finalproject_flashora
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  http: ^1.2.2
  flutter_bloc: ^8.1.6
  flutter_svg: ^2.0.10+1
  shimmer: ^3.0.0
  lottie: ^3.1.2
  equatable: ^2.0.5
  go_router: ^14.2.1
  google_fonts: ^6.2.1
  intl: ^0.19.0
  flutter_local_notifications: ^17.2.1+2
  mockito: ^5.4.4
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  either_dart: ^1.0.0
  shared_preferences: ^2.2.3
  cloud_firestore: ^4.14.0
  get_it: ^7.7.0
  image_picker: ^1.1.2
  firebase_storage: ^11.7.7
  firebase_messaging: ^14.9.4
  flutter_multi_formatter: ^2.13.0
  qr_flutter: ^4.1.0
  pdf: ^3.11.0
  path_provider: ^2.1.4
  syncfusion_flutter_datepicker: ^26.2.8
  open_file: ^3.3.2
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.11

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/
    - assets/icons/
    - .env
